# Inherits docker-compose.yml

services:
  app:
    image: audiobox:app
    build:
      context: .
      target: gobuilder
    networks:
      - default
    ports:
      - "${PORT:-8080}:8090"
    environment:
      - APP_ENV=development
      - VERSION=${VERSION:-(untracked)}
    volumes:
      - .:/app

    develop:
      watch:
        - action: rebuild
          path: .